### ISSUE TITLE
How to clear the list & add new items

### ISSUE THREAD

**Issue by 1matin** [Seeloewen/Random-Item-Giver-Updater-Legacy#9]
Hi & thanks for your great application.
How can I completely empty the list & rewrite it after?

**Comment by Seeloewen** [comment]
Thank you for the nice review! 
I'm unsure what list you are talking about though. Can you give me some more information?

**Comment by 1matin** [comment]
Hello again. When I download the datapack, seems that that has some default items, such as raw gold or dirt in the random items list. What I want is to fully empty the list & just let me add my items

**Comment by Seeloewen** [comment]
Unfortunately, you will need to remove the items manually as the feature for removing items will come at a later point in development.
Basically, you would need to navigate (in the datapack) to **data\randomitemgiver\loot_tables\1item\main.json**. In that file, delete everything and paste this code:
```
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stone"
        }
      ]
    }
  ]
}
```
After you put this in the code, you can use the Random Item Giver Updater to add the items. Please note that for the Random Item Giver Updater to work correctly, there has to be one default item in the loot table, thats why I put the minecraft:stone there.

Also, since we're only editing the main file, the datapack settings like changing item amount or item type won't work anymore.

**Comment by 1matin** [comment]
Thanks!
